name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: reset permissions 
        run: docker run --rm -v "$PWD":/project bash:latest chown --recursive $(id -u):$(id -g) /project

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Build Java application
        run: |
          docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project gradle:jdk17 gradle build

      - name: Build Docker Image
        run: docker image build -t docker-java-jar:latest .

      # 1. Graceful Interrupt (SIGINT) & Stop (SIGTERM)
      - name: Interrupt and Stop existing container
        run: |
          if [ $(docker ps -q -f name=my-app-container) ]; then
            echo "Gracefully stopping container..."
            docker stop --time=10 my-app-container
          fi

      # 2. Cleanup / Removal
      - name: Remove stopped container
        run: |
          if [ $(docker ps -a -q -f name=my-app-container) ]; then
            echo "Removing existing container..."
            docker rm -f my-app-container
          fi

      # 3. Start Container (Detached Mode)
      - name: Run new container
        run: |
          docker run -d --name my-app-container -p 8080:8080 --restart unless-stopped docker-java-jar:latest
